version: "3.7"
services:
  app:
    container_name: express-typescript
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file: .env
    environment:
      - PORT=${PORT}
    ports:
      - 5000:8080
